services:
  web:
    build: ./frontend/app
    depends_on:
      - api
    ports:
      - 4173:4173
    develop:
      watch:
        - path: ./frontend/app/package.json
          action: rebuild
        - path: ./frontend/app/package-lock.json
          action: rebuild
        - path: ./frontend/app
          target: /app
          action: sync
  api:
    build: ./backend
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /
          action: sync
    networks:
      - prisma-network
networks:
  prisma-network:
    name: prisma-network
